export interface HadithBook {
  id: string
  name: string
  arabicName: string
  author: string
  authorDeath: string
  totalHadiths: number
  totalChapters: number
  grade: string
  description: string
  hasTamil: boolean
}

export const HADITH_BOOKS: HadithBook[] = [
  {
    id: 'bukhari',
    name: 'Sahih al-Bukhari',
    arabicName: 'صحيح البخاري',
    author: 'Imam Muhammad al-Bukhari',
    authorDeath: '194 – 256 AH (870 CE)',
    totalHadiths: 7563,
    totalChapters: 97,
    grade: 'Sahih (Highest Authenticity)',
    description: 'Universally accepted as the most authentic collection of Prophetic traditions after the Holy Quran.',
    hasTamil: true,
  },
  {
    id: 'muslim',
    name: 'Sahih Muslim',
    arabicName: 'صحيح مسلم',
    author: 'Imam Muslim ibn al-Hajjaj',
    authorDeath: '204 – 261 AH (875 CE)',
    totalHadiths: 7500,
    totalChapters: 56,
    grade: 'Sahih (Highest Authenticity)',
    description: 'Renowned for its rigorous thematic organization, chains of transmission, and strict authenticity.',
    hasTamil: true,
  },
  {
    id: 'tirmidhi',
    name: 'Jami` at-Tirmidhi',
    arabicName: 'جامع الترمذي',
    author: 'Imam Abu Isa Muhammad at-Tirmidhi',
    authorDeath: '209 – 279 AH (892 CE)',
    totalHadiths: 3956,
    totalChapters: 49,
    grade: 'Sunan (Graded Traditions)',
    description: 'Famous for categorizing traditions by legal jurisprudence and documenting Hadith authenticity grades.',
    hasTamil: true,
  },
  {
    id: 'abudawud',
    name: 'Sunan Abi Dawud',
    arabicName: 'سنن أبي داود',
    author: 'Imam Abu Dawud as-Sijistani',
    authorDeath: '202 – 275 AH (889 CE)',
    totalHadiths: 5274,
    totalChapters: 43,
    grade: 'Sunan (Legal Traditions)',
    description: 'Focuses primarily on legal rulings (Ahkam), ethical guidelines, and daily practices of the Prophet (ﷺ).',
    hasTamil: true,
  },
  {
    id: 'nasai',
    name: 'Sunan an-Nasa\'i',
    arabicName: 'سنن النسائي',
    author: 'Imam Ahmad ibn Shu\'ayb an-Nasa\'i',
    authorDeath: '215 – 303 AH (915 CE)',
    totalHadiths: 5760,
    totalChapters: 52,
    grade: 'Sunan (Rigorous Scrutiny)',
    description: 'Contains one of the most stringent filters of narrators among the four Sunan collections.',
    hasTamil: true,
  },
  {
    id: 'ibnmajah',
    name: 'Sunan Ibn Majah',
    arabicName: 'سنن ابن ماجه',
    author: 'Imam Ibn Majah al-Qazwini',
    authorDeath: '209 – 273 AH (887 CE)',
    totalHadiths: 4341,
    totalChapters: 37,
    grade: 'Sunan (Comprehensive)',
    description: 'Completes the Kutub al-Sittah (Six Major Books) with rare traditions and practical rulings.',
    hasTamil: true,
  },
]

// Fallback Chapter Definitions for immediate fast rendering
export const DEFAULT_BOOK_SECTIONS: Record<string, Record<string, string>> = {
  bukhari: {
    '1': 'Revelation (بدء الوحي)',
    '2': 'Belief (الإيمان)',
    '3': 'Knowledge (العلم)',
    '4': 'Ablution / Wudu (الوضوء)',
    '5': 'Bathing / Ghusl (الغسل)',
    '6': 'Menstrual Periods (الحيض)',
    '7': 'Rubbing hands and feet with dust / Tayammum (التيمم)',
    '8': 'Prayers / Salat (الصلاة)',
    '9': 'Times of the Prayers (مواقيت الصلاة)',
    '10': 'Call to Prayers / Adhan (الأذان)',
    '11': 'Friday Prayer (الجمعة)',
    '12': 'Fear Prayer (صلاة الخوف)',
    '13': 'The Two Festivals / Eids (العيدين)',
    '14': 'Witr Prayer (الوتر)',
    '15': 'Invoking Allah for Rain / Istisqa (الاستسقاء)',
    '16': 'Eclipses (الكسوف)',
    '17': 'Prostration During Recitation (سجود القرآن)',
    '18': 'Shortening the Prayers / Taqsir (تقصير الصلاة)',
    '19': 'Prayer at Night / Tahajjud (التهجد)',
    '20': 'Virtues of Prayer at Mecca & Medina (فضل الصلاة في مسجد مكة والمدينة)',
    '21': 'Actions while Praying (العمل في الصلاة)',
    '22': 'Forgetfulness in Prayer (السهو)',
    '23': 'Funerals / Jana\'iz (الجنائز)',
    '24': 'Obligatory Charity / Zakat (الزكاة)',
    '25': 'Obligatory Charity after Ramadan / Sadaqat-ul-Fitr (صدقة الفطر)',
    '26': 'Pilgrimage / Hajj (الحج)',
    '27': 'Minor Pilgrimage / Umrah (العمرة)',
    '28': 'Pilgrims Prevented from Completing Hajj (المحصر)',
    '29': 'Penalty of Hunting while in Ihram (جزاء الصيد)',
    '30': 'Virtues of Medina (فضائل المدينة)',
    '31': 'Fasting / Sawm (الصوم)',
    '32': 'Praying at Night in Ramadan / Taraweeh (صلاة التراويح)',
    '33': 'Retiring to a Mosque for Remembrance / I\'tikaf (الاعتكاف)',
    '34': 'Sales and Trade (البيوع)',
    '35': 'Sales in which a Price is paid for Goods to be Delivered Later (السلم)',
    '36': 'Hiring (الإجارة)',
    '37': 'Transferance of a Debt (الحوالات)',
    '38': 'Representation / Agency (الوكالة)',
    '39': 'Agriculture and Cultivation (المزارعة)',
    '40': 'Distribution of Water (المساقاة)',
    '41': 'Loans, Payment of Loans, Freezing of Property (الاستقراض)',
    '42': 'Lost and Found Property (اللقطة)',
    '43': 'Oppressions / Injustices (المظالم)',
    '44': 'Partnership (الشركة)',
    '45': 'Mortgaging (الرهن)',
    '46': 'Manumission of Slaves (العتق)',
    '47': 'Gifts and the Excellence of Giving Them (الهبة وفضلها)',
    '48': 'Witnesses (الشهادات)',
    '49': 'Peacemaking (الصلح)',
    '50': 'Conditions (الشروط)',
    '51': 'Wills and Testaments (الوصايا)',
    '52': 'Fighting for the Cause of Allah / Jihad (الجهاد والسير)',
    '53': 'One-fifth of Booty to the Cause of Allah / Khumus (فرض الخمس)',
    '54': 'Jizyah and Mawaada\'ah (الجزية والموادعة)',
    '55': 'Beginning of Creation (بدء الخلق)',
    '56': 'Prophets (أحاديث الأنبياء)',
    '57': 'Virtues and Merits of the Prophet (ﷺ) (مناقب قريش)',
    '58': 'Companions of the Prophet (ﷺ) (فضائل أصحاب النبي صلى الله عليه وسلم)',
    '59': 'Merits of the Helpers in Madinah / Ansar (مناقب الأنصار)',
    '60': 'Military Expeditions led by the Prophet (ﷺ) / Maghazi (المغازي)',
    '61': 'Prophetic Commentary on the Quran / Tafsir (تفسير القرآن)',
    '62': 'Virtues of the Quran (فضائل القرآن)',
    '63': 'Wedlock, Marriage / Nikah (النكاح)',
    '64': 'Divorce / Talaq (الطلاق)',
    '65': 'Supporting the Family (النفقات)',
    '66': 'Food, Meals (الأطعمة)',
    '67': 'Sacrifice on Occasion of Birth / Aqiqa (العقيقة)',
    '68': 'Hunting, Slaughtering (الذبائح والصيد)',
    '69': 'Al-Adha Festival Sacrifice (الأضاحي)',
    '70': 'Drinks (الأشربة)',
    '71': 'Patients / Illness (المرضى)',
    '72': 'Medicine / Tibb (الطب)',
    '73': 'Dress, Clothing (اللباس)',
    '74': 'Good Manners and Form / Adab (الأدب)',
    '75': 'Asking Permission (الاستئذان)',
    '76': 'Invocations and Supplications / Du\'a (الدعوات)',
    '77': 'Heart-Melting Traditions / Riqaq (الرقاق)',
    '78': 'Divine Will / Qadar (القدر)',
    '79': 'Oaths and Vows (الأيمان والنذور)',
    '80': 'Expiation for Unfulfilled Oaths (كفارات الأيمان)',
    '81': 'Laws of Inheritance / Fara\'id (الفرائض)',
    '82': 'Prescribed Punishments / Hudud (الحدود)',
    '83': 'Blood Money / Diyat (الديات)',
    '84': 'Apostates (استتابة المرتدين)',
    '85': 'Coercion / Under Duress (الإكراه)',
    '86': 'Tricks and Stratagems (الحيل)',
    '87': 'Interpretation of Dreams (تعبير الرؤيا)',
    '88': 'Afflictions and the End of the World / Fitan (الفتن)',
    '89': 'Judgments / Ahkam (الأحكام)',
    '90': 'Wishes (التمني)',
    '91': 'Accepting Information Given by a Truthful Person (أخبار الآحاد)',
    '92': 'Holding Fast to the Quran and Sunnah (الاعتصام بالكتاب والسنة)',
    '93': 'Oneness, Uniqueness of Allah / Tawheed (التوحيد)',
  },
  muslim: {
    '1': 'The Book of Faith (كتاب الإيمان)',
    '2': 'The Book of Purification (كتاب الطهارة)',
    '3': 'The Book of Menstruation (كتاب الحيض)',
    '4': 'The Book of Prayers (كتاب الصلاة)',
    '5': 'The Book of Mosques and Places of Prayer (كتاب المساجد ومواضع الصلاة)',
    '6': 'The Book of Prayer - Travellers (كتاب صلاة المسافرين وقصرها)',
    '7': 'The Book of Prayer - Friday (كتاب الجمعة)',
    '8': 'The Book of Prayer - Two Eids (كتاب صلاة العيدين)',
    '9': 'The Book of Prayer - Rain / Istisqa (كتاب صلاة الاستسقاء)',
    '10': 'The Book of Prayer - Eclipses (كتاب الكسوف)',
    '11': 'The Book of Prayer - Funerals (كتاب الجنائز)',
    '12': 'The Book of Zakat (كتاب الزكاة)',
    '13': 'The Book of Fasting (كتاب الصيام)',
    '14': 'The Book of I\'tikaf (كتاب الاعتكاف)',
    '15': 'The Book of Pilgrimage / Hajj (كتاب الحج)',
    '16': 'The Book of Marriage (كتاب النكاح)',
    '17': 'The Book of Suckling (كتاب الرضاع)',
    '18': 'The Book of Divorce (كتاب الطلاق)',
    '19': 'The Book of Invoking Curses / Li\'an (كتاب اللعان)',
    '20': 'The Book of Emancipating Slaves (كتاب العتق)',
    '21': 'The Book of Business Transactions (كتاب البيوع)',
    '22': 'The Book of Musaqah / Sharecropping (كتاب المساقاة)',
    '23': 'The Book of Rules of Inheritance (كتاب الفرائض)',
    '24': 'The Book of Gifts (كتاب الهبات)',
    '25': 'The Book of Wills (كتاب الوصية)',
    '26': 'The Book of Vows (كتاب النذر)',
    '27': 'The Book of Oaths (كتاب الأيمان)',
    '28': 'The Book of Oaths, Murders, Retaliation (كتاب القسامة والمحاربين والقصاص والديات)',
    '29': 'The Book of Legal Punishments / Hudud (كتاب الحدود)',
    '30': 'The Book of Judicial Decisions (كتاب الأقضية)',
    '31': 'The Book of Lost Property (كتاب اللقطة)',
    '32': 'The Book of Jihad and Expeditions (كتاب الجهاد والسير)',
    '33': 'The Book on Government / Imarah (كتاب الإمارة)',
    '34': 'The Book of Hunting, Slaughter, Animals (كتاب الصيد والذبائح وما يؤكل من الحيوان)',
    '35': 'The Book of Sacrifices (كتاب الأضاحي)',
    '36': 'The Book of Drinks (كتاب الأشربة)',
    '37': 'The Book of Clothes and Adornment (كتاب اللباس والزينة)',
    '38': 'The Book of Manners and Etiquette (كتاب الآداب)',
    '39': 'The Book on Salutations and Greetings (كتاب السلام)',
    '40': 'The Book of General Behavior (كتاب الألفاظ من الأدب وغيرها)',
    '41': 'The Book of Poetry (كتاب الشعر)',
    '42': 'The Book of Dreams (كتاب الرؤيا)',
    '43': 'The Book of Virtues (كتاب الفضائل)',
    '44': 'The Book of the Merits of the Companions (كتاب فضائل الصحابة رضي الله تعالى عنهم)',
    '45': 'The Book of Virtue, Enjoining Good Ties (كتاب البر والصلة والآداب)',
    '46': 'The Book of Destiny / Qadr (كتاب القدر)',
    '47': 'The Book of Knowledge (كتاب العلم)',
    '48': 'The Book of Remembrance, Supplication, Repentance (كتاب الذكر والدعاء والتوبة والاستغفار)',
    '49': 'The Book of Heart-Melting Traditions (كتاب الرقاق)',
    '50': 'The Book of Repentance (كتاب التوبة)',
    '51': 'Characteristics of Hypocrites (كتاب صفات المنافقين وأحكامهم)',
    '52': 'Characteristics of the Day of Judgment, Paradise, Hell (كتاب صفة القيامة والجنة والنار)',
    '53': 'The Book of Paradise, its Description and Bliss (كتاب الجنة وصفة نعيمها وأهلها)',
    '54': 'The Book of Tribulations and Portents of the Last Hour (كتاب الفتن وأشراط الساعة)',
    '55': 'The Book of Zuhd / Asceticism (كتاب الزهد والرقائق)',
    '56': 'The Book of Commentary on the Quran / Tafsir (كتاب التفسير)',
  },
}
