export interface HisnulMuslimItem {
  id: string
  chapterId: string
  chapterTitleEn: string
  chapterTitleTa: string
  occasionEn: string
  occasionTa: string
  arabic: string
  transliteration: string
  translationEn: string
  translationTa: string
  reference: string
  referenceTa: string
  repeatCount?: number
}

export const HISNUL_MUSLIM_CATEGORIES = [
  { id: 'all', titleEn: 'All Supplications', titleTa: 'அனைத்து துஆக்கள்' },
  { id: 'morning_evening', titleEn: 'Morning & Evening Adhkar', titleTa: 'காலை & மாலை திக்ருகள்' },
  { id: 'sleep_wake', titleEn: 'Sleep & Waking Up', titleTa: 'தூக்கம் & விழித்தல்' },
  { id: 'prayer_mosque', titleEn: 'Salah & Mosque Etiquette', titleTa: 'தொழுகை & பள்ளிவாசல்' },
  { id: 'anxiety_grief', titleEn: 'Distress, Anxiety & Sickness', titleTa: 'கவலை, நோய் & நிவாரணம்' },
  { id: 'forgiveness', titleEn: 'Repentance & Istighfar', titleTa: 'பாவமன்னிப்பு & தவ்பா' },
  { id: 'home_daily', titleEn: 'Home, Meals & Travel', titleTa: 'வீடு, உணவு & பயணம்' },
  { id: 'protection', titleEn: 'Protection & Safety', titleTa: 'தீங்குகளிலிருந்து பாதுகாப்பு' },
]

export const HISNUL_MUSLIM_DUAS: HisnulMuslimItem[] = [
  // 1. MORNING & EVENING
  {
    id: 'hm_sayyidul_istighfar',
    chapterId: 'morning_evening',
    chapterTitleEn: 'Morning & Evening Remembrance',
    chapterTitleTa: 'காலை & மாலை திக்ருகள்',
    occasionEn: 'Chief Supplication for Seeking Forgiveness (Recited every morning and evening)',
    occasionTa: 'பாவமன்னிப்பின் தலைவர் (காலை மற்றும் மாலையில் ஓத வேண்டியது)',
    arabic: 'اللَّهُمَّ أَنْتَ رَبِّي لَا إِلَهَ إِلَّا أَنْتَ، خَلَقْتَنِي وَأَنَا عَبْدُكَ، وَأَنَا عَلَى عَهْدِكَ وَوَعْدِكَ مَا اسْتَطَعْتُ، أَعُوذُ بِكَ مِنْ شَرِّ مَا صَنَعْتُ، أَبُوءُ لَكَ بِنِعْمَتِكَ عَلَيَّ، وَأَبُوءُ لَكَ بِذَنْبِي فَاغْفِرْ لِي، فَإِنَّهُ لَا يَغْفِرُ الذُّنُوبَ إِلَّا أَنْتَ',
    transliteration: 'Allāhumma anta Rabbī lā ilāha illā ant, khalaqtanī wa anā ‘abduk, wa anā ‘alā ‘ahdika wa wa‘dika ma-staṭa‘t, a‘ūdhu bika min sharri mā ṣana‘t, abū’u laka bi-ni‘matika ‘alay, wa abū’u laka bi-dhanbī faghfir lī fa-innahū lā yaghfiru-dh-dhunūba illā ant.',
    translationEn: 'O Allah! You are my Lord; none has the right to be worshipped but You. You created me and I am Your slave, and I am faithful to my covenant and promise to You as much as I can. I seek refuge with You from all the evil I have done. I acknowledge Your favors upon me and I confess all my sins. So forgive me, for none forgives sins except You.',
    translationTa: 'யா அல்லாஹ்! நீயே என் இறைவன். உன்னைத் தவிர வணக்கத்திற்குரியவன் யாருமில்லை. நீயே என்னை படைத்தாய்; நான் உன் அடிமை. என்னால் முடிந்த வரை உன் உடன்படிக்கையிலும் வாக்குறுதியிலும் நிலைத்திருக்கிறேன். நான் செய்த தீமைகளிலிருந்து உன்னிடம் பாதுகாப்புத் தேடுகிறேன். நீ எனக்கு அளித்த அருட்கொடைகளை ஒப்புக்கொள்கிறேன்; என் பாவங்களையும் ஒப்புக்கொள்கிறேன். எனவே என்னை மன்னித்தருள்வாயாக! நிச்சயமாக உன்னைத் தவிர வேறு எவரும் பாவங்களை மன்னிக்க முடியாது.',
    reference: 'Sahih al-Bukhari 6306',
    referenceTa: 'ஸஹீஹ் அல்-புகாரி 6306',
    repeatCount: 1,
  },
  {
    id: 'hm_morning_asbahna',
    chapterId: 'morning_evening',
    chapterTitleEn: 'Morning & Evening Remembrance',
    chapterTitleTa: 'காலை & மாலை திக்ருகள்',
    occasionEn: 'Upon Entering the Morning',
    occasionTa: 'காலை விடியும்போது ஓதும் துஆ',
    arabic: 'أَصْبَحْنَا وَأَصْبَحَ الْمُلْكُ لِلَّهِ، وَالْحَمْدُ لِلَّهِ، لَا إِلَهَ إِلَّا اللَّهُ وَحْدَهُ لَا شَرِيكَ لَهُ، لَهُ الْمُلْكُ وَلَهُ الْحَمْدُ وَهُوَ عَلَى كُلِّ شَيْءٍ قَدِيرٌ',
    transliteration: 'Aṣbaḥnā wa aṣbaḥal-mulku lillāh, wal-ḥamdu lillāh, lā ilāha illallāhu waḥdahū lā sharīka lah, lahul-mulku wa lahul-ḥamdu wa huwa ‘alā kulli shay’in qadīr.',
    translationEn: 'We have entered the morning and the kingdom belongs to Allah; all praise is for Allah. There is no deity worthy of worship except Allah alone, without partner. To Him belongs the sovereignty and to Him belongs all praise, and He has power over all things.',
    translationTa: 'நாங்களும் காலைப் பொழுதை அடைந்தோம்; அரசாட்சியும் அல்லாஹ்வுக்குரியதாகவே காலைப் பொழுதை அடைந்தது. எல்லாப் புகழும் அல்லாஹ்வுக்கே! வணக்கத்திற்குரியவன் அல்லாஹ்வைத் தவிர வேறு யாருமில்லை; அவன் தனித்தவன், அவனுக்கு இணைதுணை இல்லை.',
    reference: 'Sahih Muslim 2723',
    referenceTa: 'ஸஹீஹ் முஸ்லிம் 2723',
    repeatCount: 1,
  },
  {
    id: 'hm_protection_bismillah',
    chapterId: 'protection',
    chapterTitleEn: 'Protection from Harm & Evil',
    chapterTitleTa: 'தீங்குகளிலிருந்து பாதுகாப்பு',
    occasionEn: 'Shield Against Any Harm in Earth and Heaven (3 times in Morning & Evening)',
    occasionTa: 'வானம் மற்றும் பூமியின் அனைத்து தீங்குகளிலிருந்தும் காக்கும் கவசம் (காலை & மாலையில் 3 முறை)',
    arabic: 'بِسْمِ اللَّهِ الَّذِي لَا يَضُرُّ مَعَ اسْمِهِ شَيْءٌ فِي الْأَرْضِ وَلَا فِي السَّمَاءِ وَهُوَ السَّمِيعُ الْعَلِيمُ',
    transliteration: 'Bismillāh-il-ladhī lā yaḍurru ma‘as-mihī shay’un fil-arḍi wa lā fis-samā’i wa huwas-Samī‘ul-‘Alīm.',
    translationEn: 'In the Name of Allah, with Whose Name nothing on the earth or in the heavens can cause harm, and He is the All-Hearing, the All-Knowing.',
    translationTa: 'எந்த அல்லாஹ்வின் திருப்பெயரைக் கொண்டு பூமியிலோ வானத்திலோ உள்ள எந்தப் பொருளும் தீங்கு செய்ய முடியாதோ அந்த அல்லாஹ்வின் திருப்பெயரால் (பாதுகாப்புத் தேடுகிறேன்); அவனே செவியேற்பவனாகவும் நன்கறிபவனாகவும் இருக்கிறான்.',
    reference: 'Sunan Abi Dawud 5088; Jami` at-Tirmidhi 3388',
    referenceTa: 'ஸுனன் அபீதாவூத் 5088; ஜாமிஉத் திர்மிதி 3388',
    repeatCount: 3,
  },
  {
    id: 'hm_raditu_billah',
    chapterId: 'morning_evening',
    chapterTitleEn: 'Morning & Evening Remembrance',
    chapterTitleTa: 'காலை & மாலை திக்ருகள்',
    occasionEn: 'Pleasure in Allah, Islam, and the Messenger ﷺ (Guarantees Jannah - 3 times)',
    occasionTa: 'அல்லாஹ்வையும் இஸ்லாத்தையும் நபிகளாரையும் மனதார ஏற்று ஓதும் துஆ (சொர்க்கம் உறுதியாகும் - 3 முறை)',
    arabic: 'رَضِيتُ بِاللَّهِ رَبًّا، وَبِالْإِسْلَامِ دِينًا، وَبِمُحَمَّدٍ صَلَّى اللَّهُ عَلَيْهِ وَسَلَّمَ نَبِيًّا',
    transliteration: 'Raḍītu billāhi Rabban, wa bil-Islāmi dīnan, wa bi-Muḥammadin (ṣallallāhu ‘alayhi wa sallam) Nabiyyā.',
    translationEn: 'I am pleased with Allah as my Lord, with Islam as my religion, and with Muhammad (peace and blessings of Allah be upon him) as my Prophet.',
    translationTa: 'அல்லாஹ்வை என் இறைவனாகவும், இஸ்லாத்தை என் மார்க்கமாகவும், முஹம்மத் (ஸல்) அவர்களை என் நபியாகவும் நான் மனப்பூர்வமாக ஏற்றுக்கொண்டேன்.',
    reference: 'Sunan Abi Dawud 5072; Jami` at-Tirmidhi 3389',
    referenceTa: 'ஸுனன் அபீதாவூத் 5072; ஜாமிஉத் திர்மிதி 3389',
    repeatCount: 3,
  },

  // 2. SLEEP & WAKING UP
  {
    id: 'hm_before_sleep',
    chapterId: 'sleep_wake',
    chapterTitleEn: 'Sleep & Waking Up',
    chapterTitleTa: 'தூக்கம் & விழித்தல்',
    occasionEn: 'Before Laying Down to Sleep',
    occasionTa: 'இரவில் தூங்கச் செல்லும் போது',
    arabic: 'بِاسْمِكَ اللَّهُمَّ أَمُوتُ وَأَحْيَا',
    transliteration: 'Bismikallāhumma amūtu wa aḥyā.',
    translationEn: 'In Your Name, O Allah, I die and I live.',
    translationTa: 'யா அல்லாஹ்! உன் பெயரால் நான் மரணிக்கிறேன் (தூங்குகிறேன்), உன் பெயரால் நான் உயிர்ப்பிக்கிறேன் (விழிக்கிறேன்).',
    reference: 'Sahih al-Bukhari 6312',
    referenceTa: 'ஸஹீஹ் அல்-புகாரி 6312',
    repeatCount: 1,
  },
  {
    id: 'hm_upon_waking',
    chapterId: 'sleep_wake',
    chapterTitleEn: 'Sleep & Waking Up',
    chapterTitleTa: 'தூக்கம் & விழித்தல்',
    occasionEn: 'Upon Waking Up from Sleep',
    occasionTa: 'தூக்கத்திலிருந்து விழித்தெழும் போது',
    arabic: 'الْحَمْدُ لِلَّهِ الَّذِي أَحْيَانَا بَعْدَ مَا أَمَاتَنَا وَإِلَيْهِ النُّشُورُ',
    transliteration: 'Al-ḥamdu lillāh-illadhī aḥyānā ba‘da mā amātanā wa ilayhin-nushūr.',
    translationEn: 'All praise is for Allah, Who gave us life after having caused us to die, and unto Him is the resurrection.',
    translationTa: 'நம்மை மரணிக்கச் செய்த பின் (தூங்கச் செய்த பின்) மீண்டும் நம்மை உயிர்ப்பித்த அல்லாஹ்வுக்கே எல்லாப் புகழும்! அவனிடமே நாம் ஒன்று திரட்டப்பட வேண்டியுள்ளது.',
    reference: 'Sahih al-Bukhari 6314',
    referenceTa: 'ஸஹீஹ் அல்-புகாரி 6314',
    repeatCount: 1,
  },

  // 3. MOSQUE & PRAYER
  {
    id: 'hm_enter_mosque',
    chapterId: 'prayer_mosque',
    chapterTitleEn: 'Mosque & Salah Supplications',
    chapterTitleTa: 'தொழுகை & பள்ளிவாசல்',
    occasionEn: 'Upon Entering the Mosque (Right foot first)',
    occasionTa: 'பள்ளிவாசலில் நுழையும் போது (வலது காலை முன்வைத்து)',
    arabic: 'اللَّهُمَّ افْتَحْ لِي أَبْوَابَ رَحْمَتِكَ',
    transliteration: 'Allāhummaf-taḥ lī abwāba raḥmatik.',
    translationEn: 'O Allah! Open for me the gates of Your Mercy.',
    translationTa: 'யா அல்லாஹ்! உனது அருளின் வாசல்களை எனக்குத் திறந்து விடுவாயாக!',
    reference: 'Sahih Muslim 713',
    referenceTa: 'ஸஹீஹ் முஸ்லிம் 713',
    repeatCount: 1,
  },
  {
    id: 'hm_leave_mosque',
    chapterId: 'prayer_mosque',
    chapterTitleEn: 'Mosque & Salah Supplications',
    chapterTitleTa: 'தொழுகை & பள்ளிவாசல்',
    occasionEn: 'Upon Leaving the Mosque (Left foot first)',
    occasionTa: 'பள்ளிவாசலை விட்டு வெளியேறும் போது (இடது காலை முன்வைத்து)',
    arabic: 'اللَّهُمَّ إِنِّي أَسْأَلُكَ مِنْ فَضْلِكَ',
    transliteration: 'Allāhumma innī as’aluka min faḍlik.',
    translationEn: 'O Allah! I ask You for Your Bounty and Favor.',
    translationTa: 'யா அல்லாஹ்! உனது பேரருளை உன்னிடமிருந்து நான் வேண்டுகிறேன்.',
    reference: 'Sahih Muslim 713',
    referenceTa: 'ஸஹீஹ் முஸ்லிம் 713',
    repeatCount: 1,
  },
  {
    id: 'hm_after_salah_istighfar',
    chapterId: 'prayer_mosque',
    chapterTitleEn: 'Mosque & Salah Supplications',
    chapterTitleTa: 'தொழுகை & பள்ளிவாசல்',
    occasionEn: 'Immediately After Concluding Any Obligatory Prayer',
    occasionTa: 'கடமையான தொழுகையை முடித்தவுடன் ஓதும் துஆ',
    arabic: 'أَسْتَغْفِرُ اللَّهَ (ثَلاثاً)، اللَّهُمَّ أَنْتَ السَّلامُ وَمِنْكَ السَّلامُ، تَبَارَكْتَ يَا ذَا الجَلالِ وَالإِكْرَامِ',
    transliteration: 'Astaghfirullāh (3x), Allāhumma antas-Salāmu wa minkas-salām, tabārakta yā Dhal-Jalāli wal-Ikrām.',
    translationEn: 'I seek forgiveness from Allah (3 times). O Allah! You are Peace, and from You comes peace. Blessed are You, O Possessor of Majesty and Honor.',
    translationTa: 'அல்லாஹ்விடம் பாவமன்னிப்புக் கோருகிறேன் (3 முறை). யா அல்லாஹ்! நீயே சாந்தியளிப்பவன்; உன்னிடமிருந்தே சாந்தி உண்டாகிறது. மாண்பும் கண்ணியமும் உடையவனே! நீ மிக்க பாக்கியவான்.',
    reference: 'Sahih Muslim 591',
    referenceTa: 'ஸஹீஹ் முஸ்லிம் 591',
    repeatCount: 1,
  },
  {
    id: 'hm_ayat_al_kursi_post_prayer',
    chapterId: 'prayer_mosque',
    chapterTitleEn: 'Mosque & Salah Supplications',
    chapterTitleTa: 'தொழுகை & பள்ளிவாசல்',
    occasionEn: 'Ayat al-Kursi Recited After Every Obligatory Salah (Key to Jannah)',
    occasionTa: 'கடமையான தொழுகைக்குப் பின் ஓதப்படும் ஆயத்துல் குர்ஸீ (சொர்க்கத்தின் திறவுகோல்)',
    arabic: 'اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ ۚ لَا تَأْخُذُهُ سِنَةٌ وَلَا نَوْمٌ ۚ لَهُ مَا فِي السَّمَاوَاتِ وَمَا فِي الْأَرْضِ ۗ مَن ذَا الَّذِي يَشْفَعُ عِندَهُ إِلَّا بِإِذْنِهِ ۚ يَعْلَمُ مَا بَيْنَ أَيْدِيهِمْ وَمَا خَلْفَهُمْ ۖ وَلَا يُحِيطُونَ بِشَيْءٍ مِّنْ عِلْمِهِ إِلَّا بِمَا شَاءَ ۚ وَسِعَ كُرْسِيُّهُ السَّمَاوَاتِ وَالْأَرْضَ ۖ وَلَا يَئُودُهُ حِفْظُهُمَا ۚ وَهُوَ الْعَلِيُّ الْعَظِيمُ',
    transliteration: 'Allāhu lā ilāha illā huwal-Ḥayyul-Qayyūm, lā ta’khudhuhū sinatun wa lā nawm, lahū mā fis-samāwāti wa mā fil-arḍ, man dhal-ladhī yashfa‘u ‘indahū illā bi-idhnih, ya‘lamu mā bayna aydīhim wa mā khalfahum, wa lā yuḥīṭūna bi-shay’in min ‘ilmihī illā bi-mā shā’, wasi‘a kursiyyuhus-samāwāti wal-arḍ, wa lā ya’ūduhū ḥifẓuhumā, wa huwal-‘Aliyyul-‘Aẓīm.',
    translationEn: 'Allah! There is no deity except Him, the Ever-Living, the Sustainer of all existence. Neither drowsiness overtakes Him nor sleep. To Him belongs whatever is in the heavens and whatever is on the earth. Who is it that can intercede with Him except by His permission? He knows what is before them and what will be after them, and they encompass not a thing of His knowledge except for what He wills. His Kursi extends over the heavens and the earth, and their preservation tires Him not. And He is the Most High, the Most Great.',
    translationTa: 'அல்லாஹ் - அவனைத் தவிர வணக்கத்திற்குரிய இறைவன் வேறு யாருமில்லை; அவன் என்றென்றும் உயிருடன் இருப்பவன்; அனைத்தையும் காத்துப் பரிபாலிப்பவன்; அவனுக்கு சிறு உறக்கமோ ஆழ்ந்த தூக்கமோ ஏற்படாது; வானங்களிலும் பூமியிலும் உள்ளவை அனைத்தும் அவனுக்கே உரியன; அவன் அனுமதியின்றி அவனிடம் யார் பரிந்து பேச முடியும்? அவன் அவர்களுக்கு முன்னுள்ளவற்றையும் பின்னுள்ளவற்றையும் நன்கறிவான்; அவனது பேரறிவிலிருந்து அவன் நாடியதைத் தவிர எதனையும் மனிதர்கள் அறிய மாட்டார்கள்; அவனது ஆசனம் வானங்களையும் பூமியையும் சூழ்ந்திருக்கிறது; அவ்விரண்டையும் பாதுகாப்பது அவனுக்குச் சிரமமானதல்ல; அவனே மகா உன்னதமானவன், மகத்தானவன்.',
    reference: 'Sunan an-Nasa\'i (Al-Kubra 9848); Sahih Ibn Hibban 1801',
    referenceTa: 'ஸுனன் அந்-நஸாயீ (அல்-குப்ரா 9848); ஸஹீஹ் இப்னு ஹிப்பான் 1801',
    repeatCount: 1,
  },

  // 4. ANXIETY, DISTRESS & SICKNESS
  {
    id: 'hm_anxiety_debts',
    chapterId: 'anxiety_grief',
    chapterTitleEn: 'Anxiety, Distress & Sickness',
    chapterTitleTa: 'கவலை, நோய் & நிவாரணம்',
    occasionEn: 'Supplication for Anxiety, Sorrow, Laziness, and Overwhelming Debts',
    occasionTa: 'கவலை, சோம்பல், பயம் மற்றும் கடனின் சுமையிலிருந்து விடுபட ஓதும் துஆ',
    arabic: 'اللَّهُمَّ إِنِّي أَعُوذُ بِكَ مِنَ الْهَمِّ وَالْحَزَنِ، وَالْعَجْزِ وَالْكَسَلِ، وَالْبُخْلِ وَالْجُبْنِ، وَضَلَعِ الدَّيْنِ وَغَلَبَةِ الرِّجَالِ',
    transliteration: 'Allāhumma innī a‘ūdhu bika minal-hammi wal-ḥazan, wal-‘ajzi wal-kasal, wal-bukhli wal-jubn, wa ḍala‘id-dayni wa ghalabatir-rijāl.',
    translationEn: 'O Allah, I seek refuge in You from grief and sadness, from weakness and laziness, from miserliness and cowardice, from being heavily in debt and from being overpowered by other people.',
    translationTa: 'யா அல்லாஹ்! கவலை, துக்கம், இயலாமை, சோம்பல், கஞ்சத்தனம், கோழைத்தனம், கடனின் சுமை மற்றும் மனிதர்களின் அடக்குமுறை ஆகியவற்றிலிருந்து உன்னிடம் நான் பாதுகாப்புத் தேடுகிறேன்.',
    reference: 'Sahih al-Bukhari 2893',
    referenceTa: 'ஸஹீஹ் அல்-புகாரி 2893',
    repeatCount: 1,
  },
  {
    id: 'hm_visiting_the_sick',
    chapterId: 'anxiety_grief',
    chapterTitleEn: 'Anxiety, Distress & Sickness',
    chapterTitleTa: 'கவலை, நோய் & நிவாரணம்',
    occasionEn: 'When Visiting the Sick (Supplication for Quick Shifa / Healing - 7 times)',
    occasionTa: 'நோயாளிகளை நலம் விசாரிக்கும் போது உடல்நலத் தேறுதலுக்கு ஓதும் துஆ (7 முறை)',
    arabic: 'أَسْأَلُ اللَّهَ الْعَظِيمَ رَبَّ الْعَرْشِ الْعَظِيمِ أَنْ يَشْفِيَكَ',
    transliteration: 'As’alullāhal-‘Aẓīm, Rabbal-‘Arshil-‘Aẓīm, an yashfiyak.',
    translationEn: 'I ask Almighty Allah, Lord of the Magnificent Throne, to heal and cure you.',
    translationTa: 'மகத்தான அர்ஷின் அதிபதியான மகத்தான அல்லாஹ்விடம் அவன் உமக்குக் குணமளிக்க வேண்டுமென வேண்டுகிறேன்.',
    reference: 'Sunan Abi Dawud 3106; Jami` at-Tirmidhi 2083',
    referenceTa: 'ஸுனன் அபீதாவூத் 3106; ஜாமிஉத் திர்மிதி 2083',
    repeatCount: 7,
  },

  // 5. HOME, MEALS & TRAVEL
  {
    id: 'hm_leaving_home',
    chapterId: 'home_daily',
    chapterTitleEn: 'Home, Meals & Travel',
    chapterTitleTa: 'வீடு, உணவு & பயணம்',
    occasionEn: 'Upon Leaving the House (Surrounded by angelic protection)',
    occasionTa: 'வீட்டை விட்டு வெளியேறும் போது (வானவர்களின் பாதுகாப்பு கிட்டும்)',
    arabic: 'بِسْمِ اللَّهِ، تَوَكَّلْتُ عَلَى اللَّهِ، وَلَا حَوْلَ وَلَا قُوَّةَ إِلَّا بِاللَّهِ',
    transliteration: 'Bismillāhi tawakkaltu ‘alallāh, wa lā ḥawla wa lā quwwata illā billāh.',
    translationEn: 'In the Name of Allah, I place my full trust in Allah; there is no power nor strength except with Allah.',
    translationTa: 'அல்லாஹ்வின் பெயரால் (வெளியேறுகிறேன்); அல்லாஹ்வின் மீதே நான் முழு நம்பிக்கை வைக்கிறேன்; அல்லாஹ்வின் உதவியின்றி எவ்வித ஆற்றலும் சக்தியும் இல்லை.',
    reference: 'Sunan Abi Dawud 5095; Jami` at-Tirmidhi 3426',
    referenceTa: 'ஸுனன் அபீதாவூத் 5095; ஜாமிஉத் திர்மிதி 3426',
    repeatCount: 1,
  },
  {
    id: 'hm_entering_home',
    chapterId: 'home_daily',
    chapterTitleEn: 'Home, Meals & Travel',
    chapterTitleTa: 'வீடு, உணவு & பயணம்',
    occasionEn: 'Upon Entering the House (Brings barakah and peace)',
    occasionTa: 'வீட்டினுள் நுழையும் போது (பரக்கத்தும் அமைதியும் உண்டாகும்)',
    arabic: 'بِسْمِ اللَّهِ وَلَجْنَا، وَبِسْمِ اللَّهِ خَرَجْنَا، وَعَلَى رَبِّنَا تَوَكَّلْنَا',
    transliteration: 'Bismillāhi walajnā, wa bismillāhi kharajnā, wa ‘alā Rabbinā tawakkalnā.',
    translationEn: 'In the Name of Allah we enter, and in the Name of Allah we leave, and upon our Lord we place our trust.',
    translationTa: 'அல்லாஹ்வின் பெயரால் நாம் நுழைகிறோம்; அல்லாஹ்வின் பெயரால் நாம் வெளியேறுகிறோம்; மேலும் நம்முடைய இறைவன் மீதே நாம் நம்பிக்கை வைக்கிறோம்.',
    reference: 'Sunan Abi Dawud 5096',
    referenceTa: 'ஸுனன் அபீதாவூத் 5096',
    repeatCount: 1,
  },
  {
    id: 'hm_travel_supplication',
    chapterId: 'home_daily',
    chapterTitleEn: 'Home, Meals & Travel',
    chapterTitleTa: 'வீடு, உணவு & பயணம்',
    occasionEn: 'Upon Boarding Any Vehicle or Embarking on a Journey',
    occasionTa: 'வாகனத்தில் ஏறும் போது மற்றும் பயணத்தை துவக்கும் போது',
    arabic: 'سُبْحَانَ الَّذِي سَخَّرَ لَنَا هَٰذَا وَمَا كُنَّا لَهُ مُقْرِنِينَ وَإِنَّا إِلَىٰ رَبِّنَا لَمُنقَلِبُونَ',
    transliteration: 'Subḥānal-ladhī sakh-khara lanā hādhā wa mā kunnā lahū muqrinīn, wa innā ilā Rabbinā lamunqalibūn.',
    translationEn: 'Glory is to Him Who has subjected this to us, and we could never have subdued it by ourselves. And indeed, unto our Lord we shall surely return.',
    translationTa: 'இதனை நமக்கு வசப்படுத்தித் தந்தவன் மிகத் தூயவன்; (அவன் அருளாதிருந்தால்) நாம் இதனை கட்டுப்படுத்தும் சக்தி பெற்றவர்களாக இருந்திருக்க மாட்டோம். நிச்சயமாக நாம் நமது இறைவனிடமே திரும்பிச் செல்லக்கூடியவர்கள்.',
    reference: 'Sahih Muslim 1342; Quran 43:13-14',
    referenceTa: 'ஸஹீஹ் முஸ்லிம் 1342; திருக்குர்ஆன் 43:13-14',
    repeatCount: 1,
  },
  {
    id: 'hm_breaking_fast',
    chapterId: 'home_daily',
    chapterTitleEn: 'Home, Meals & Travel',
    chapterTitleTa: 'வீடு, உணவு & பயணம்',
    occasionEn: 'Upon Breaking the Fast (Iftar)',
    occasionTa: 'நோன்பு துறக்கும் போது (இஃப்தார்)',
    arabic: 'ذَهَبَ الظَّمَأُ وَابْتَلَّتِ الْعُرُوقُ، وَثَبَتَ الأَجْرُ إِنْ شَاءَ اللَّهُ',
    transliteration: 'Dhahabadh-dhama’u wab-tallatil-‘urūqu, wa thabatal-ajru inshā’Allāh.',
    translationEn: 'The thirst has gone, the veins are moistened, and the reward is confirmed, if Allah wills.',
    translationTa: 'தாகம் தீர்ந்தது; நரம்புகள் நனைந்தன; அல்லாஹ் நாடினால் நற்கூலியும் உறுதியாகிவிட்டது.',
    reference: 'Sunan Abi Dawud 2357',
    referenceTa: 'ஸுனன் அபீதாவூத் 2357',
    repeatCount: 1,
  },
  {
    id: 'hm_istikharah',
    chapterId: 'prayer_mosque',
    chapterTitleEn: 'Mosque & Salah Supplications',
    chapterTitleTa: 'தொழுகை & பள்ளிவாசல்',
    occasionEn: 'Salat al-Istikharah (Seeking Allah’s Guidance in Any Decision)',
    occasionTa: 'இஸ்திகாரா தொழுகையின் துஆ (காரியங்களில் அல்லாஹ்வின் நல்ல வழிகாட்டலை வேண்ட)',
    arabic: 'اللَّهُمَّ إِنِّي أَسْتَخِيرُكَ بِعِلْمِكَ، وَأَسْتَقْدِرُكَ بِقُدْرَتِكَ، وَأَسْأَلُكَ مِنْ فَضْلِكَ الْعَظِيمِ، فَإِنَّكَ تَقْدِرُ وَلَا أَقْدِرُ، وَتَعْلَمُ وَلَا أَعْلَمُ، وَأَنْتَ عَلَّامُ الْغُيُوبِ',
    transliteration: 'Allāhumma innī astakhīruka bi-‘ilmika, wa asta-qdiruka bi-qudratika, wa as’aluka min faḍlikal-‘Aẓīm, fa-innaka taqdiru wa lā aqdir, wa ta‘lamu wa lā a‘lam, wa Anta ‘Allāmul-ghuyūb.',
    translationEn: 'O Allah! I seek Your guidance through Your Knowledge, and I seek ability through Your Power, and I ask You of Your Great Bounty. For You are capable and I am not, You know and I do not, and You are the Knower of all unseen things.',
    translationTa: 'யா அல்லாஹ்! உனது பேரறிவின் மூலம் நன்மையானதைத் தேர்ந்தெடுக்க உன்னிடம் வழிகாட்டல் வேண்டுகிறேன்; உனது பேராற்றலின் மூலம் சக்தி வேண்டுகிறேன்; உனது மகத்தான அருளை வேண்டுகிறேன். நிச்சயமாக நீயே ஆற்றலுடையவன், எனக்கு எவ்வித ஆற்றலும் இல்லை; நீயே அனைத்தையும் அறிபவன், நான் எதையும் அறியமாட்டேன்; மறைவானவற்றை முழுமையாக அறிபவன் நீயே!',
    reference: 'Sahih al-Bukhari 1162',
    referenceTa: 'ஸஹீஹ் அல்-புகாரி 1162',
    repeatCount: 1,
  },
]
