/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    screens: {
      sm: '640px',
      md: '768px',
      lg: '1024px',
      xl: '1280px',
      '2xl': '1536px',
    },
    extend: {
      colors: {
        "secondary-container": "var(--color-secondary-container)",
        "tertiary-fixed-dim": "var(--color-tertiary)",
        "error": "var(--color-error)",
        "primary": "var(--color-primary)",
        "tertiary-container": "var(--color-tertiary-container)",
        "secondary": "var(--color-secondary)",
        "surface-container-lowest": "var(--bg-app)",
        "tertiary": "var(--color-tertiary)",
        "on-tertiary-fixed": "#002113",
        "on-secondary-fixed-variant": "#4a3d7c",
        "on-primary": "#3f008e",
        "on-surface-variant": "var(--text-on-surface-variant)",
        "outline": "var(--text-outline)",
        "on-primary-container": "#ede0ff",
        "surface-container": "var(--bg-surface-container)",
        "on-primary-fixed": "#25005a",
        "outline-variant": "var(--border-outline-variant)",
        "on-tertiary": "#003824",
        "primary-fixed": "#eaddff",
        "secondary-fixed-dim": "var(--color-secondary)",
        "surface-variant": "var(--bg-surface-high)",
        "inverse-primary": "#732ee4",
        "primary-fixed-dim": "var(--color-primary)",
        "on-tertiary-container": "#76ffc2",
        "inverse-on-surface": "#283044",
        "on-primary-fixed-variant": "#5a00c6",
        "inverse-surface": "#dae2fd",
        "surface-tint": "var(--color-primary)",
        "on-secondary-fixed": "#1e0e4e",
        "surface-dim": "var(--bg-surface-low)",
        "secondary-fixed": "#e7deff",
        "tertiary-fixed": "#6ffbbe",
        "on-background": "var(--text-on-surface)",
        "on-tertiary-fixed-variant": "#005236",
        "error-container": "#93000a",
        "background": "var(--bg-app)",
        "surface-container-low": "var(--bg-surface-low)",
        "surface-container-high": "var(--bg-surface-high)",
        "surface-container-highest": "var(--bg-surface-highest)",
        "primary-container": "var(--color-primary-container)",
        "on-secondary": "#332664",
        "on-error-container": "#ffdad6",
        "surface": "var(--bg-surface)",
        "on-error": "#690005",
        "surface-bright": "var(--bg-surface-high)",
        "on-surface": "var(--text-on-surface)",
        "on-secondary-container": "#baabf3"
      },
      borderRadius: {
        "sm": "0.5rem",
        "DEFAULT": "1rem",
        "md": "1.5rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
      spacing: {
        "section-gap": "32px",
        "container-margin": "24px",
        "gutter": "16px",
        "card-padding": "20px"
      },
      fontFamily: {
        sans: ["'Plus Jakarta Sans'", "sans-serif"],
        "plus-jakarta": ["'Plus Jakarta Sans'", "sans-serif"],
        "noto-serif": ["'Noto Serif'", "serif"],
        "label-caps": ["'Plus Jakarta Sans'", "sans-serif"],
        "display-quran-mobile": ["'Noto Serif'", "serif"],
        "body-lg": ["'Plus Jakarta Sans'", "sans-serif"],
        "display-quran": ["'Noto Serif'", "serif"],
        "h2": ["'Plus Jakarta Sans'", "sans-serif"],
        "h1": ["'Plus Jakarta Sans'", "sans-serif"],
        "body-md": ["'Plus Jakarta Sans'", "sans-serif"]
      },
      fontSize: {
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "display-quran-mobile": ["32px", { lineHeight: "170%", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "display-quran": ["40px", { lineHeight: "180%", fontWeight: "400" }],
        "h2": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "h1": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }]
      }
    }
  },
  plugins: [],
}
